### ISSUE TITLE
Error: Type 'OverflowBoxFit' not found.

### ISSUE THREAD

**Issue by jheske** [peiffer-innovations/json_theme#162]
This occurs on version json_theme 6+, but not on version 5.0.2. Thank you in advance to anyone who can provide insight into this issue!

build_runner works with version 6, but including this line causes the error so the app can't run.

```
  final themeStr =
      await rootBundle.loadString('assets/themes/appainter_theme.json');
```

The error is 

```
Error (Xcode): [+2151 ms] ../../../.pub-cache/hosted/pub.dev/json_theme-6.4.1/lib/src/codec/theme_decoder.dart:9203:10: Error: Type 'OverflowBoxFit' not found.

[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 15 Pro Max.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:705:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

It may be conflicting with drift and/or freezed packages.  Here is my pubspec file.
```name: drift_local_database_example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.8.3
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0
  equatable: ^2.0.5
  drift_db_viewer: ^2.0.0
  provider: 6.1.1
  font_awesome_flutter: ^10.7.0
  json_theme: ^6.4.1
  dio: ^5.4.1
  retrofit: ^4.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.15.0
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/themes/

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore```

**Comment by johnwhitehead91** [comment]
Use this in your pubspec.yaml as a temporary work around until the fix has been published to pub.dev
json_theme:
  git:
    url: https://github.com/peiffer-innovations/json_theme.git
    ref: main
    path: json_theme

**Comment by johnwhitehead91** [comment]
I am assuming you are on a lower version of Flutter? Run flutter upgrade and try again. Worked for myself at least.

**Comment by FrasKc** [comment]
Same error here, running flutter upgrade don't work for me. 

Here is a piece of my pubspec file: 
```
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_crashlytics: ^3.0.11
  another_flushbar: ^1.12.29
  fluttertoast: ^8.1.2
  hooks_riverpod: ^2.4.9
  crypt: ^4.2.1
  introduction_screen: ^3.1.4
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  equatable: ^2.0.3
  font_awesome_flutter: ^10.5.0
  json_theme: ^6.4.1
  flutter_native_splash: ^2.2.18
  percent_indicator: ^4.0.0
  shared_preferences: ^2.0.15
  mask_text_input_formatter: ^2.4.0
  rive: ^0.13.1
  stop_watch_timer: ^3.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  image_picker: ^1.0.1
  unicons: ^2.1.0
  location: ^5.0.0
  workmanager: ^0.5.1
  wakelock: ^0.6.2
  rxdart: ^0.27.7
  flutter_background_service: ^5.0.5
  flutter_background_service_ios: ^5.0.0
  flutter_background_service_android: ^6.2.2
  permission_handler: ^11.2.0
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.1.11
  flutter_native_image: ^0.0.6+1
  flutter_screenutil: ^5.9.0
```   

And here is my error while running xcode build : 
```
Error (Xcode): ../../.pub-cache/hosted/pub.dev/json_theme-6.4.1/lib/src/codec/theme_decoder.dart:9203:10: Error: Type 'OverflowBoxFit' not found.

Could not build the application for the simulator.
Error launching application on iPhone 15.
```

**Comment by jheske** [comment]
Underneath `dependencies:` use

    json_theme:
        git:
          url: https://github.com/peiffer-innovations/json_theme.git
          ref: main
          path: json_theme

That requires `intl: ^0.19.0`. Upgrading `intl` caused its own conflicts, which I fixed with  an override: 

    dependency_overrides:
          intl: 0.19.0
