### ISSUE TITLE
IconData usage prevents icon tree shaking in flutter 3.10

### ISSUE THREAD

**Issue by countfloyd** [peiffer-innovations/json_theme#95]
Trying to do a 'flutter build web' on a flutter project using the latest json_theme. Getting the following error:

```
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///Users/curtis/.pub-cache/hosted/pub.dev/json_theme-5.0.2+6/lib/src/codec/theme_decoder.dart:4811:16
Target web_release_bundle failed: Exception: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      IconTreeShaker._findConstants (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:307:7)
<asynchronous suspension>
#2      IconTreeShaker._getIconData (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:108:45)
<asynchronous suspension>
#3      IconTreeShaker.subsetFont (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:172:5)
<asynchronous suspension>
#4      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:127:25)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:105:3)
<asynchronous suspension>
#7      WebReleaseBundle.build (package:flutter_tools/src/build_system/targets/web.dart:385:29)
<asynchronous suspension>
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#10     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#11     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#12     WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:81:34)
<asynchronous suspension>
#13     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:191:5)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

**Comment by efreibe** [comment]
Same here

**Comment by jpeiffer** [comment]
This isn't an issue with the package as much as it is a change with Flutter for Web.  Basically, because this package allows you to reference icons dynamically, Flutter cannot tree shake icons because it cannot know at compile time if you might reference an icon or not (and if you think about the purpose of this package, that makes complete sense).

You just need to change how you're doing your builds by adding the `--no-tree-shake-icons` flag to your build.  For example:

```
flutter build web --release --no-tree-shake-icons
```

**Comment by Cryoware** [comment]
This issue happens when building both an APK or App Bundle on Flutter 3.10.6.

So am wondering if the issue would or could be fixed without having to disable tree shaking optimizations? I have not tried to compile for other platforms at this time.

Thanks!

```
Running Gradle task 'assembleRelease'...                        
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///C:/Users/JimStrong/AppData/Local/Pub/Cache/hosted/pub.dev/json_theme-5.0.2+4/lib/src/codec/theme_decoder.dart:4811:16
Target aot_android_asset_bundle failed: Exception: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.
```
